### PR TITLE
Feature/create images from text

### PR DESCRIPTION
**Pull request by dscohen75**
# Description

A new notebook was added in the notebooks folder, images_from_text.ipynb, for creating jpg images using text in handwriting like fonts chosen and downloaded from Google Fonts GitHub Repo.

The notebook can be more easily viewed [here in Google Colab](https://colab.research.google.com/drive/1wx0bzKhIuhhk8fLtwJA5hcszWpP66kUU?usp=sharing).

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, but not tested (may need new tests)

## Has This Been Tested

- [ ] Yes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by imdeja — APPROVED** [review]
Good job exploring the images from text.

**Comment by rrherr** [comment]
@dscohen75 can you share a Colab link? It will be easier to view your notebook there.

**Comment by dscohen75** [comment]
Yes, done!
A link to the Colab notebook can now be found in the PR description.

**Review by BrokenShell — APPROVED** [review]
looks good

**Pull request merged**
