### PR TITLE
Notebook with function for generating synthetic data

### PR DESCRIPTION
**Pull request by EEdwardsA**
# Contains notebook for generating n synthetic data samples; a folder of txt scraped stories; a folder of children's handwriting fonts

Replace with description of PR

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [X] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [X] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by BrokenShell — COMMENTED** [review]
The notebook looks good. Did you mean to upload over 200 files?

**Comment by EEdwardsA** [comment]
> Did you mean to upload over 200 files?

I did, for the sake of reproducibility, but now that I'm thinking about it some more, maybe that's unnecessary?

**Review by jproctor-rebecca — APPROVED** [review]
thank you for being explicit and adding the licensing information and citing your references in your comments/documentation - an excellent practice of transfer of knowledge to current and future teams

**Review by BrokenShell — APPROVED** [review]

**Review by trevorjamesmartin — APPROVED** [review]
looks good

**Pull request merged**
